[package]
name = "floatwidgets"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24.5"

[dependencies.reqwest]
version = "0.11.14"
features = ["blocking"]

[dependencies.sdl2]
video = "0.35.2"
features = ["image"]
